---
- name: this playbook install httpd
  hosts: localhost
  become: true
  tasks:
  - name: install package
    yum: 
      name: httpd 
      state: installed
    notify: start apache

  handlers:
  - name: start apache
    service:
      name: httpd
      state: started 
